#!/bin/sh
set -eu

clear

PROJECT_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
SCRIPT_DIR="${PROJECT_ROOT}/scripts"
LOG_DIR="${PROJECT_ROOT}/results/run_logs"
REPORT_PATH="${LOG_DIR}/all_retriever_outputs.md"

mkdir -p "${LOG_DIR}"

cat > "${REPORT_PATH}" <<EOF
# Retriever RQ Summaries

Generated by \`run_pipeline.sh\`.

EOF

append_rq_summaries_to_report() {
  title="$1"
  log_path="$2"
  summary_path="${log_path}.rq_summaries"
  python - "$log_path" > "${summary_path}" <<'PY'
import re
import sys
from pathlib import Path

ansi_re = re.compile(r"\x1b\[[0-9;]*m")
path = Path(sys.argv[1])
capture = False
seen_summary = False
progress_re = re.compile(
    r"(?:\d+%\||\|\s*\d+/\d+|\b(?:sample|question|transition|row|pair|reader)s?/s\])"
)

for raw_line in path.read_text(errors="replace").replace("\r", "\n").splitlines():
    line = ansi_re.sub("", raw_line)
    stripped = line.strip()
    if progress_re.search(stripped):
        continue

    if re.fullmatch(r"(RQ[123].*summary|Bootstrap CI summary)", stripped):
        if seen_summary:
            print()
            print()
        seen_summary = True
        capture = True

    if capture and (
        stripped.startswith("Wrote ")
        or stripped.startswith("==>")
        or stripped.startswith("done:")
        or stripped.endswith("pipeline complete.")
    ):
        capture = False
        continue

    if capture:
        print(line)
PY
  if [ -s "${summary_path}" ]; then
    {
      printf '\n## %s\n\n' "$title"
      printf '```text\n'
      cat "${summary_path}"
      printf '\n```\n'
    } >> "${REPORT_PATH}"
  fi
  rm -f "${summary_path}"
}

run_stage() {
  name="$1"
  script="$2"
  log_name="$3"
  include_in_report="${4:-yes}"
  log_path="${LOG_DIR}/${log_name}"
  status_path="${LOG_DIR}/${log_name}.status"
  printf '\033[1;35m\n========== %s ==========\033[0m\n' "$name"
  rm -f "${status_path}"
  (sh "${SCRIPT_DIR}/${script}" 2>&1; printf '%s\n' "$?" > "${status_path}") | tee "${log_path}"
  if [ "$include_in_report" = "yes" ]; then
    append_rq_summaries_to_report "$name" "$log_path"
  fi
  status="$(cat "${status_path}")"
  rm -f "${status_path}"
  if [ "$status" -ne 0 ]; then
    printf '\033[1;31mStage failed: %s (exit %s)\033[0m\n' "$name" "$status" >&2
    exit "$status"
  fi
}

run_retriever() {
  name="$1"
  script="$2"
  log_name="$3"
  run_stage "Running ${name}" "$script" "$log_name"
}

run_stage "Downloading QUIT test split" "download_quit_test.sh" "download_quit_test.log" "no"

run_retriever "BM25" "run_bm25.sh" "bm25.log"
run_retriever "SPLADE" "run_splade.sh" "splade.log"
run_retriever "DPR" "run_dpr.sh" "dpr.log"
run_retriever "ColBERT" "run_colbert.sh" "colbert.log"
run_retriever "BGE" "run_bge.sh" "bge.log"
run_retriever "ReasonIR" "run_reasonir.sh" "reasonir.log"

run_stage "Selecting qualitative examples" "select_qualitative_examples.sh" "qualitative_examples.log" "no"

printf '\033[1;35m\n========== Exporting paper outputs ==========\033[0m\n'
python "${PROJECT_ROOT}/src/export_paper_outputs.py" \
  --results-dir "${PROJECT_ROOT}/results" \
  --output-dir "${PROJECT_ROOT}/outputs"

printf '\033[1;32m\nPipeline complete.\033[0m\n'
printf 'Combined RQ summary report: %s\n' "${REPORT_PATH}"
printf 'Qualitative examples: %s\n' "${PROJECT_ROOT}/results/examples"
printf 'Paper tables: %s\n' "${PROJECT_ROOT}/outputs/tables"
printf 'Paper figures: %s\n' "${PROJECT_ROOT}/outputs/figures"
